services:


  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
    expose:
      - 3306

#  oracle-db:
#    image: container-registry.oracle.com/database/enterprise:latest
#    environment:
#      - ORACLE_SID=ORCLCDB
#      - ORACLE_PDB=ORCLPDB1
#      - ORACLE_PWD=Oracle_123
#    ports:
#      - 1521:1521
#    volumes:
#      - oracle-data:/opt/oracle/oradata

volumes:
  db_data:
#  oracle-data: